CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS people (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    name BYTEA NOT NULL,
    limit_distance BOOLEAN NOT NULL DEFAULT TRUE,
    user_id UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);